const LOW = 0.25;
const MED = 0.5;
const HIGH = 0.75;

/**
 * we use the range -1 to + 1 to block for a particular layer
 * for eg. Area priority would be from AREA_BASE - Steps.HIGH to order.AREA + Steps.HIGH
 * This exists to avoid same priorities or overlapping priorities between different layers
 */

const WATERWAY_BASE = 1;
const AREA_BASE = 2;
const HIGHWAY_BASE = 3;
const RAIL_BASE = 4;
const POINT_BASE = 5;
const NON_INTERACTIVE_BASE = 6;
const LABEL_BASE = 7;
const EXTRUSION_BASE = 8;
const INTERACTIVE_BASE = 9;

export const LOWEST_PRIORITY = 0;

export enum WATERWAY {
  MINUS_3 = WATERWAY_BASE - HIGH,
  MINUS_2 = WATERWAY_BASE - MED,
  MINUS_1 = WATERWAY_BASE - LOW,
  ZERO = WATERWAY_BASE,
  PLUS_1 = WATERWAY_BASE + LOW,
  PLUS_2 = WATERWAY_BASE + MED,
  PLUS_3 = WATERWAY_BASE + HIGH,
}
export enum AREA {
  MINUS_3 = AREA_BASE - HIGH,
  MINUS_2 = AREA_BASE - MED,
  MINUS_1 = AREA_BASE - LOW,
  ZERO = AREA_BASE,
  PLUS_1 = AREA_BASE + LOW,
  PLUS_2 = AREA_BASE + MED,
  PLUS_3 = AREA_BASE + HIGH,
}

export enum HIGHWAY {
  MINUS_3 = HIGHWAY_BASE - HIGH,
  MINUS_2 = HIGHWAY_BASE - MED,
  MINUS_1 = HIGHWAY_BASE - LOW,
  ZERO = HIGHWAY_BASE,
  PLUS_1 = HIGHWAY_BASE + LOW,
  PLUS_2 = HIGHWAY_BASE + MED,
  PLUS_3 = HIGHWAY_BASE + HIGH,
}

export enum RAIL {
  MINUS_3 = RAIL_BASE - HIGH,
  MINUS_2 = RAIL_BASE - MED,
  MINUS_1 = RAIL_BASE - LOW,
  ZERO = RAIL_BASE,
  PLUS_1 = RAIL_BASE + LOW,
  PLUS_2 = RAIL_BASE + MED,
  PLUS_3 = RAIL_BASE + HIGH,
}

export enum NON_INTERACTIVE {
  MINUS_3 = NON_INTERACTIVE_BASE - HIGH,
  MINUS_2 = NON_INTERACTIVE_BASE - MED,
  MINUS_1 = NON_INTERACTIVE_BASE - LOW,
  ZERO = NON_INTERACTIVE_BASE,
  PLUS_1 = NON_INTERACTIVE_BASE + LOW,
  PLUS_2 = NON_INTERACTIVE_BASE + MED,
  PLUS_3 = NON_INTERACTIVE_BASE + HIGH,
}

export enum POINT {
  MINUS_3 = POINT_BASE - HIGH,
  MINUS_2 = POINT_BASE - MED,
  MINUS_1 = POINT_BASE - LOW,
  ZERO = POINT_BASE,
  PLUS_1 = POINT_BASE + LOW,
  PLUS_2 = POINT_BASE + MED,
  PLUS_3 = POINT_BASE + HIGH,
}

export enum LABEL {
  MINUS_3 = LABEL_BASE - HIGH,
  MINUS_2 = LABEL_BASE - MED,
  MINUS_1 = LABEL_BASE - LOW,
  ZERO = LABEL_BASE,
  PLUS_1 = LABEL_BASE + LOW,
  PLUS_2 = LABEL_BASE + MED,
  PLUS_3 = LABEL_BASE + HIGH,
}

export enum INTERACTIVE {
  MINUS_3 = INTERACTIVE_BASE - HIGH,
  MINUS_2 = INTERACTIVE_BASE - MED,
  MINUS_1 = INTERACTIVE_BASE - LOW,
  ZERO = INTERACTIVE_BASE,
  PLUS_1 = INTERACTIVE_BASE + LOW,
  PLUS_2 = INTERACTIVE_BASE + MED,
  PLUS_3 = INTERACTIVE_BASE + HIGH,
}

export enum EXTRUSION {
  MINUS_3 = EXTRUSION_BASE - HIGH,
  MINUS_2 = EXTRUSION_BASE - MED,
  MINUS_1 = EXTRUSION_BASE - LOW,
  ZERO = EXTRUSION_BASE,
  PLUS_1 = EXTRUSION_BASE + LOW,
  PLUS_2 = EXTRUSION_BASE + MED,
  PLUS_3 = EXTRUSION_BASE + HIGH,
}
